### ISSUE TITLE
Login should redirect to previous page

### ISSUE THREAD

**Issue by Evidlo** [purdue-epics-ims/boilerconnect#12]
Currently after you Login, the website redirects you to the front page.  This will be annoying when someone has to rebrowse to whatever page they were looking at before.

This can be easily fixed by modifying this line in the login form(already there)
    `<input type="hidden" name="next" value="">`

Whatever is in `value` is where django will redirect the user upon hitting the submit button.  Find a way to set this to the user's previous page.

**Comment by matthewchiou** [comment]
I tried to use http_referer, but it didn't work. It might take a bit longer.

**Comment by matchiou** [comment]
I did it with http_referer, and it worked. However, there was an underlying problem. If I typed my password wrong for the first time, then after I login I would be redirected to login page again. Same problem happened when I log out then log back in. This need to be fixed.
