### ISSUE TITLE
front_page view error when no orgs

### ISSUE THREAD

**Issue by Evidlo** [purdue-epics-ims/boilerconnect#2]
The front page view has an error when there is nothing in the database.  Find a more robust way to get a random organization that doesn't get an error if there's nothing in the database.

**Comment by matchiou** [comment]
What should be displayed if there is nothing in the database? I figured out another way to pass the query-set and it passes nothing if there's nothing in the data base. However, this might change the html styling a lot.

**Comment by Evidlo** [comment]
Just pass a zero length list to the template for loop
