### ISSUE TITLE
'guardian_tags' is not a valid tag library

### ISSUE THREAD

**Issue by matchiou** [purdue-epics-ims/boilerconnect#36]
Apparently it's not valid

**Comment by Evidlo** [comment]
Paste the full error

**Comment by Evidlo** [comment]
Also run `from guardian import templatetags` in the shell.

**Comment by matchiou** [comment]
Exception Value:  
'guardian_tags' is not a valid tag library: ImportError raised loading guardian.templatetags.guardian_tags: cannot import name get_library
Exception Location: /Library/Python/2.7/site-packages/django/template/defaulttags.py in load, line 1163

**Comment by matchiou** [comment]
It is a run-time error produces by the server. So I don't think running anything in the shell would help

**Comment by Evidlo** [comment]
Do you get an error when you import that class
